DROP DATABASE IF EXISTS `sistema`;
CREATE DATABASE IF NOT EXISTS `sistema`;
USE `sistema`;

DROP TABLE IF EXISTS `contatos`;
CREATE TABLE IF NOT EXISTS `contatos` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(100) NOT NULL,
	`EMPRESA` VARCHAR(80) DEFAULT NULL,
	`CARGO` VARCHAR(80) DEFAULT NULL,
	`EMAIL`	VARCHAR(80) DEFAULT NULL,
	`ATIVO` TINYINT(1) NOT NULL DEFAULT 1,
	`CRIADO_EM` DATETIME NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_BIN;

DROP TABLE IF EXISTS `telefones`;
CREATE TABLE IF NOT EXISTS `telefones` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`CONTATO_ID` INT(11) NOT NULL, 
	`TIPO` ENUM('CELULAR','FIXO','WHATSAPP','COMERCIAL') NOT NULL,
	`NUMERO` VARCHAR(30) NOT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `fk_telefones_contatos`
		FOREIGN KEY (`CONTATO_ID`) REFERENCES `contatos` (`ID`)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_BIN;

DROP TABLE IF EXISTS `enderecos`;
CREATE TABLE IF NOT EXISTS `enderecos` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`CONTATO_ID` INT(11) NOT NULL,
	`TIPO` ENUM('RESIDENCIAL','COMERCIAL','OUTRO'),
	`LOGRADOURO` VARCHAR(150) NOT NULL,
	`NUMERO` VARCHAR(10),
	`COMPLEMENTO` VARCHAR(80),
	`BAIRRO` VARCHAR(80) NOT NULL,
	`CIDADE` VARCHAR(80) NOT NULL,
	`UF` CHAR(2) NOT NULL,
	`CEP` VARCHAR(9) NOT NULL,
	`PAIS` VARCHAR(30) DEFAULT	'BRASIL',
	PRIMARY KEY (`ID`),
	CONSTRAINT `fk_enderecos_contatos`
		FOREIGN KEY (`CONTATO_ID`) REFERENCES `contatos` (`ID`)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_BIN;

DROP TABLE IF EXISTS `visitas`;
CREATE TABLE IF NOT EXISTS `visitas` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`CONTATO_ID` INT(11) NOT NULL,
	`DATA_VISITA` DATE NOT NULL,
	`HORA_VISITA` TIME NOT NULL,
	`ASSUNTO` VARCHAR(200), 
	`OBSERVACOES` TEXT,
	`STATUS` ENUM('AGENDADA','REALIZADA','CANCELADA') NOT NULL DEFAULT 'AGENDADA',
	`CRIADO_EM` DATETIME NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`ID`),
	CONSTRAINT `fk_visitas_contatos`
		FOREIGN KEY (`CONTATO_ID`) REFERENCES `contatos` (`ID`)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_BIN;